theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/check-network-outline"  # jaxtyping logo in top left
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # These additions are my own custom ones, having overridden a partial.
    twitter_name: "@PatrickKidger"
    twitter_url: "https://twitter.com/PatrickKidger"

site_name: jaxtyping
site_description: The documentation for the jaxtyping software library.
site_author: Patrick Kidger
site_url: https://docs.kidger.site/jaxtyping

repo_url: https://github.com/google/jaxtyping
repo_name: google/jaxtyping
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "_overrides"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks, typing
                    - pytkdocs_tweaks.main()
                    - typing.GENERATING_DOCUMENTATION = False

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4

nav:
    - 'index.md'
    - API:
        - 'api/array.md'
        - 'api/pytree.md'
        - 'api/runtime-type-checking.md'
        - 'api/advanced-features.md'
    - 'faq.md'
